In [13]:
import numpy as np
arr=np.random.randint(1,100,12)
print("Original Array ", arr)

# 1Dto2D
arr=arr.reshape(4,3)
print("After transforming into 2D Array ", arr)
print("Shape of Array is ", arr.shape)

# 2Dto3D
arr=arr.reshape(2,2,3)
print("3D Array is", arr)

# 3Dto1D
arr= arr.reshape(12)
print("1D", arr)

Original Array  [73 66 86 80 49 24 52 96 17 26 37  3]
After transforming into 2D Array  [[73 66 86]
 [80 49 24]
 [52 96 17]
 [26 37  3]]
Shape of Array is  (4, 3)
3D Array is [[[73 66 86]
  [80 49 24]]

 [[52 96 17]
  [26 37  3]]]
1D [73 66 86 80 49 24 52 96 17 26 37  3]
