In [1]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [5]:
np.random.shuffle(arr)
arr

array([17, 16, 13, 10, 11,  3, 13, 11, 16, 16])

In [6]:
np.unique(arr)

array([ 3, 10, 11, 13, 16, 17])

In [7]:
np.unique(arr).size

6