In [1]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [2]:
np.sum(matrix)

116

In [3]:
np.min(matrix)

3

In [7]:
np.max(matrix) 

17

In [9]:
np.min(matrix,axis=1)

array([11, 13,  3])

In [11]:
np.sum(matrix, axis=1)

array([40, 46, 30])

In [12]:
np.max(matrix, axis=0)

array([17, 16, 16])

In [13]:
np.cumsum(matrix)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [14]:
np.cumsum(matrix, axis=0)

array([[16, 11, 13],
       [33, 24, 29],
       [36, 40, 40]], dtype=int32)