In [2]:
import numpy as np
a=np.arange(1,16)
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [4]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [5]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [6]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])