In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
np.min(arr)

10

In [3]:
np.max(arr)

50

In [4]:
np.argmin(arr)

0

In [5]:
np.argmax(arr)

4

In [6]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [7]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [8]:
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])