In [2]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[5, 6],
       [7, 8]])

In [4]:
a*b

array([[ 5, 12],
       [21, 32]])

In [5]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [6]:
a**b

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)