In [1]:
import numpy as np
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [2]:
arr+2

array([3, 4, 5, 6])

In [3]:
arr*2

array([2, 4, 6, 8])

In [4]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [6]:
arr1=np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [8]:
arr+arr1

array([ 6,  8, 10, 12])